In [1]:
# import dependencies
import numpy as np
import pandas as pd

In [2]:
# read csv file
file_path = "data_original/1976-2018-senate.csv"

# create the data frame 
senate_df_original = pd.read_csv(file_path, encoding='iso-8859-1')
senate_df_original.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version
0,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Sam Steiger,republican,False,total,321236,741210,False,20171011.0
1,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Wm. Mathews Feighan,independent,False,total,1565,741210,False,20171011.0
2,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Dennis DeConcini,democrat,False,total,400334,741210,False,20171011.0
3,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Allan Norwitz,libertarian,False,total,7310,741210,False,20171011.0
4,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Bob Field,independent,False,total,10765,741210,False,20171011.0

In [3]:
# Make a copy
senate_df = senate_df_original

In [4]:
# dropping years we do not need
senate_df = senate_df[senate_df.year != 1976]
senate_df = senate_df[senate_df.year != 1978]
senate_df = senate_df[senate_df.year != 1980]
senate_df = senate_df[senate_df.year != 1982]
senate_df = senate_df[senate_df.year != 1984]
senate_df = senate_df[senate_df.year != 1986]
senate_df = senate_df[senate_df.year != 1988]
senate_df = senate_df[senate_df.year != 1990]
senate_df = senate_df[senate_df.year != 1992]
senate_df = senate_df[senate_df.year != 1994]
senate_df = senate_df[senate_df.year != 1996]
senate_df = senate_df[senate_df.year != 1998]
senate_df = senate_df[senate_df.year != 2000]
senate_df = senate_df[senate_df.year != 2002]
senate_df = senate_df[senate_df.year != 2004]
senate_df = senate_df[senate_df.year != 2006]
senate_df = senate_df[senate_df.year != 2008]
senate_df = senate_df[senate_df.year != 2010]
senate_df = senate_df[senate_df.year != 2012]
senate_df = senate_df[senate_df.year != 2014]
senate_df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version
3048,2016,Alabama,AL,1,63,41,US Senate,statewide,gen,False,Ron Crumpton,democrat,False,total,748709,2087444,False,20171011.0
3049,2016,Alabama,AL,1,63,41,US Senate,statewide,gen,False,Richard C. Shelby,republican,False,total,1335104,2087444,False,20171011.0
3050,2016,Alabama,AL,1,63,41,US Senate,statewide,gen,False,NaN,NaN,True,total,3631,2087444,False,20171011.0
3051,2016,Alaska,AK,2,94,81,US Senate,statewide,gen,False,Joe Miller,libertarian,False,total,90825,311441,False,20171011.0
3052,2016,Alaska,AK,2,94,81,US Senate,statewide,gen,False,Ted Gianoutsos,independent,False,total,1758,311441,False,20171011.0

In [6]:
# dropping columns
senate_df = senate_df.drop(columns=["state_fips", "state_cen", "state_ic", "office", "stage", "writein",
                                  "mode", "unofficial", "version"])
senate_df.head()

,year,state,state_po,district,special,candidate,party,candidatevotes,totalvotes
3048,2016,Alabama,AL,statewide,False,Ron Crumpton,democrat,748709,2087444
3049,2016,Alabama,AL,statewide,False,Richard C. Shelby,republican,1335104,2087444
3050,2016,Alabama,AL,statewide,False,NaN,NaN,3631,2087444
3051,2016,Alaska,AK,statewide,False,Joe Miller,libertarian,90825,311441
3052,2016,Alaska,AK,statewide,False,Ted Gianoutsos,independent,1758,311441

In [7]:
#renaming columns
senate_df = senate_df.rename(columns={"year": "Year", "state": "State", "state_po": "State Abbreviation", "district": "District Number",
                                    "special": "Special Election", "candidate": "Candidate", "party": "Party",
                                    "candidatevotes": "Candidate Votes", "totalvotes": "Total Votes"})
senate_df.head()

,Year,State,State Abbreviation,District Number,Special Election,Candidate,Party,Candidate Votes,Total Votes
3048,2016,Alabama,AL,statewide,False,Ron Crumpton,democrat,748709,2087444
3049,2016,Alabama,AL,statewide,False,Richard C. Shelby,republican,1335104,2087444
3050,2016,Alabama,AL,statewide,False,NaN,NaN,3631,2087444
3051,2016,Alaska,AK,statewide,False,Joe Miller,libertarian,90825,311441
3052,2016,Alaska,AK,statewide,False,Ted Gianoutsos,independent,1758,311441

In [8]:
# Create a new column with the % of the vote that the candidate received
senate_df["Candidate Percent"] = senate_df["Candidate Votes"] / senate_df["Total Votes"]
senate_df.head()

,Year,State,State Abbreviation,District Number,Special Election,Candidate,Party,Candidate Votes,Total Votes,Candidate Percent
3048,2016,Alabama,AL,statewide,False,Ron Crumpton,democrat,748709,2087444,0.358673
3049,2016,Alabama,AL,statewide,False,Richard C. Shelby,republican,1335104,2087444,0.639588
3050,2016,Alabama,AL,statewide,False,NaN,NaN,3631,2087444,0.001739
3051,2016,Alaska,AK,statewide,False,Joe Miller,libertarian,90825,311441,0.291628
3052,2016,Alaska,AK,statewide,False,Ted Gianoutsos,independent,1758,311441,0.005645

In [9]:
# Change all parties other than democrat and republican to "other"
senate_df.loc[(senate_df["Party"] != "republican") & (senate_df["Party"] != "democrat"), "Party"] = "other"
senate_df.loc[senate_df["Party"] == "other"]

,Year,State,State Abbreviation,District Number,Special Election,Candidate,Party,Candidate Votes,Total Votes,Candidate Percent
3050,2016,Alabama,AL,statewide,False,NaN,other,3631,2087444,0.001739
3051,2016,Alaska,AK,statewide,False,Joe Miller,other,90825,311441,0.291628
3052,2016,Alaska,AK,statewide,False,Ted Gianoutsos,other,1758,311441,0.005645
3054,2016,Alaska,AK,statewide,False,Margaret Stock,other,41194,311441,0.132269
3055,2016,Alaska,AK,statewide,False,Breck A. Craig,other,2609,311441,0.008377
...,...,...,...,...,...,...,...,...,...,...
3408,2018,Virginia,VA,statewide,False,NaN,other,5125,3351373,0.001529
3413,2018,West Virginia,WV,statewide,False,Rusty Hollen,other,24231,582911,0.041569
3416,2018,Wisconsin,WI,statewide,False,NaN,other,42,2657841,0.000016
3419,2018,Wyoming,WY,statewide,False,Joseph Porambo,other,5658,203420,0.027814
3420,2018,Wyoming,WY,statewide,False,NaN,other,325,203420,0.001598

In [10]:
# View final DataFrame
senate_df.head()

,Year,State,State Abbreviation,District Number,Special Election,Candidate,Party,Candidate Votes,Total Votes,Candidate Percent
3048,2016,Alabama,AL,statewide,False,Ron Crumpton,democrat,748709,2087444,0.358673
3049,2016,Alabama,AL,statewide,False,Richard C. Shelby,republican,1335104,2087444,0.639588
3050,2016,Alabama,AL,statewide,False,NaN,other,3631,2087444,0.001739
3051,2016,Alaska,AK,statewide,False,Joe Miller,other,90825,311441,0.291628
3052,2016,Alaska,AK,statewide,False,Ted Gianoutsos,other,1758,311441,0.005645

In [11]:
# Export the cleaned data tocsv
senate_df.to_csv("data_clean/senate_clean.csv", index=False)