In [2]:
import pandas as pd

In [3]:
#importing data
unemploy_2016_df = pd.read_csv('state_unemployment_2016.csv', index_col=1)
unemploy_2018_df = pd.read_csv('state_unemployment_2018.csv', index_col=1)

In [5]:
unemploy_2016_df = unemploy_2016_df.reset_index()
unemploy_2018_df = unemploy_2018_df.reset_index()

In [6]:
unemploy_2016_df

    2016 rate                 State  Rank
0         4.9         United States   NaN
1         2.9         New Hampshire   1.0
2         3.0                Hawaii   2.0
3         3.0          South Dakota   2.0
4         3.1              Nebraska   4.0
5         3.1          North Dakota   4.0
6         3.2               Vermont   6.0
7         3.3              Colorado   7.0
8         3.4                  Utah   8.0
9         3.6                  Iowa   9.0
10        3.8                 Idaho  10.0
11        3.8                 Maine  10.0
12        3.9         Massachusetts  12.0
13        3.9             Minnesota  12.0
14        4.0              Arkansas  14.0
15        4.0                Kansas  14.0
16        4.0             Wisconsin  14.0
17        4.1               Montana  17.0
18        4.1              Virginia  17.0
19        4.4               Indiana  19.0
20        4.5              Delaware  20.0
21        4.5              Maryland  20.0
22        4.6              Missouri  22.0
23        4.6                 Texas  22.0
24        4.7             Tennessee  24.0
25        4.8               Florida  25.0
26        4.8              Oklahoma  25.0
27        4.8                Oregon  25.0
28        4.9              New York  28.0
29        5.0              Michigan  29.0
30        5.0            New Jersey  29.0
31        5.0                  Ohio  29.0
32        5.0        South Carolina  29.0
33        5.1           Connecticut  33.0
34        5.1              Kentucky  33.0
35        5.1        North Carolina  33.0
36        5.2          Rhode Island  36.0
37        5.3            Washington  37.0
38        5.3               Wyoming  37.0
39        5.4               Arizona  39.0
40        5.4               Georgia  39.0
41        5.4          Pennsylvania  39.0
42        5.5            California  42.0
43        5.7                Nevada  43.0
44        5.8               Alabama  44.0
45        5.8              Illinois  44.0
46        5.8           Mississippi  44.0
47        6.1  District of Columbia  47.0
48        6.1             Louisiana  47.0
49        6.1         West Virginia  47.0
50        6.6            New Mexico  50.0
51        6.9                Alaska  51.0

In [35]:
#Renaming Column
unemploy_df_2016 = unemploy_2016_df.rename(columns={"Rank": "2016 Rank",})
unemploy_df_2016.head()

   2016 rate          State  2016 Rank
0        4.9  United States        0.0
1        2.9  New Hampshire        1.0
2        3.0         Hawaii        2.0
3        3.0   South Dakota        2.0
4        3.1       Nebraska        4.0

In [36]:
#Renaming Column
unemploy_df_2018 = unemploy_2018_df.rename(columns={"Rank": "2018 Rank",})
unemploy_df_2018.head()

   2018 rate          State  2018 Rank
0        3.9  United States        0.0
1        2.5         Hawaii        1.0
2        2.5        Vermont        1.0
3        2.6           Iowa        3.0
4        2.6  New Hampshire        3.0

In [39]:
combine_unemploy = unemploy_df_2016 [['2016 rate','State','2016 Rank']]

In [43]:
final_combine_unemploy = combine_unemploy.join(unemploy_df_2018[["2018 rate", "2018 Rank"]])

In [44]:
final_combine_unemploy

    2016 rate                 State  2016 Rank  2018 rate  2018 Rank
0         4.9         United States        0.0        3.9        0.0
1         2.9         New Hampshire        1.0        2.5        1.0
2         3.0                Hawaii        2.0        2.5        1.0
3         3.0          South Dakota        2.0        2.6        3.0
4         3.1              Nebraska        4.0        2.6        3.0
5         3.1          North Dakota        4.0        2.6        3.0
6         3.2               Vermont        6.0        2.9        6.0
7         3.3              Colorado        7.0        2.9        6.0
8         3.4                  Utah        8.0        2.9        6.0
9         3.6                  Iowa        9.0        3.0        9.0
10        3.8                 Idaho       10.0        3.0        9.0
11        3.8                 Maine       10.0        3.0        9.0
12        3.9         Massachusetts       12.0        3.1       12.0
13        3.9             Minnesota       12.0        3.2       13.0
14        4.0              Arkansas       14.0        3.2       13.0
15        4.0                Kansas       14.0        3.2       13.0
16        4.0             Wisconsin       14.0        3.3       16.0
17        4.1               Montana       17.0        3.4       17.0
18        4.1              Virginia       17.0        3.4       17.0
19        4.4               Indiana       19.0        3.5       19.0
20        4.5              Delaware       20.0        3.5       19.0
21        4.5              Maryland       20.0        3.5       19.0
22        4.6              Missouri       22.0        3.6       22.0
23        4.6                 Texas       22.0        3.6       22.0
24        4.7             Tennessee       24.0        3.6       22.0
25        4.8               Florida       25.0        3.8       25.0
26        4.8              Oklahoma       25.0        3.8       25.0
27        4.8                Oregon       25.0        3.9       27.0
28        4.9              New York       28.0        3.9       27.0
29        5.0              Michigan       29.0        3.9       27.0
30        5.0            New Jersey       29.0        3.9       27.0
31        5.0                  Ohio       29.0        4.0       31.0
32        5.0        South Carolina       29.0        4.0       31.0
33        5.1           Connecticut       33.0        4.1       33.0
34        5.1              Kentucky       33.0        4.1       33.0
35        5.1        North Carolina       33.0        4.1       33.0
36        5.2          Rhode Island       36.0        4.1       33.0
37        5.3            Washington       37.0        4.1       33.0
38        5.3               Wyoming       37.0        4.2       38.0
39        5.4               Arizona       39.0        4.3       39.0
40        5.4               Georgia       39.0        4.3       39.0
41        5.4          Pennsylvania       39.0        4.3       39.0
42        5.5            California       42.0        4.4       42.0
43        5.7                Nevada       43.0        4.5       43.0
44        5.8               Alabama       44.0        4.5       43.0
45        5.8              Illinois       44.0        4.7       45.0
46        5.8           Mississippi       44.0        4.8       46.0
47        6.1  District of Columbia       47.0        4.9       47.0
48        6.1             Louisiana       47.0        4.9       47.0
49        6.1         West Virginia       47.0        5.2       49.0
50        6.6            New Mexico       50.0        5.7       50.0
51        6.9                Alaska       51.0        6.5       51.0

In [45]:
#merging columns 
unemployment_df = final_combine_unemploy[["State", '2016 rate', '2016 Rank', '2018 rate', '2018 Rank']]
unemployment_df

                   State  2016 rate  2016 Rank  2018 rate  2018 Rank
0          United States        4.9        0.0        3.9        0.0
1          New Hampshire        2.9        1.0        2.5        1.0
2                 Hawaii        3.0        2.0        2.5        1.0
3           South Dakota        3.0        2.0        2.6        3.0
4               Nebraska        3.1        4.0        2.6        3.0
5           North Dakota        3.1        4.0        2.6        3.0
6                Vermont        3.2        6.0        2.9        6.0
7               Colorado        3.3        7.0        2.9        6.0
8                   Utah        3.4        8.0        2.9        6.0
9                   Iowa        3.6        9.0        3.0        9.0
10                 Idaho        3.8       10.0        3.0        9.0
11                 Maine        3.8       10.0        3.0        9.0
12         Massachusetts        3.9       12.0        3.1       12.0
13             Minnesota        3.9       12.0        3.2       13.0
14              Arkansas        4.0       14.0        3.2       13.0
15                Kansas        4.0       14.0        3.2       13.0
16             Wisconsin        4.0       14.0        3.3       16.0
17               Montana        4.1       17.0        3.4       17.0
18              Virginia        4.1       17.0        3.4       17.0
19               Indiana        4.4       19.0        3.5       19.0
20              Delaware        4.5       20.0        3.5       19.0
21              Maryland        4.5       20.0        3.5       19.0
22              Missouri        4.6       22.0        3.6       22.0
23                 Texas        4.6       22.0        3.6       22.0
24             Tennessee        4.7       24.0        3.6       22.0
25               Florida        4.8       25.0        3.8       25.0
26              Oklahoma        4.8       25.0        3.8       25.0
27                Oregon        4.8       25.0        3.9       27.0
28              New York        4.9       28.0        3.9       27.0
29              Michigan        5.0       29.0        3.9       27.0
30            New Jersey        5.0       29.0        3.9       27.0
31                  Ohio        5.0       29.0        4.0       31.0
32        South Carolina        5.0       29.0        4.0       31.0
33           Connecticut        5.1       33.0        4.1       33.0
34              Kentucky        5.1       33.0        4.1       33.0
35        North Carolina        5.1       33.0        4.1       33.0
36          Rhode Island        5.2       36.0        4.1       33.0
37            Washington        5.3       37.0        4.1       33.0
38               Wyoming        5.3       37.0        4.2       38.0
39               Arizona        5.4       39.0        4.3       39.0
40               Georgia        5.4       39.0        4.3       39.0
41          Pennsylvania        5.4       39.0        4.3       39.0
42            California        5.5       42.0        4.4       42.0
43                Nevada        5.7       43.0        4.5       43.0
44               Alabama        5.8       44.0        4.5       43.0
45              Illinois        5.8       44.0        4.7       45.0
46           Mississippi        5.8       44.0        4.8       46.0
47  District of Columbia        6.1       47.0        4.9       47.0
48             Louisiana        6.1       47.0        4.9       47.0
49         West Virginia        6.1       47.0        5.2       49.0
50            New Mexico        6.6       50.0        5.7       50.0
51                Alaska        6.9       51.0        6.5       51.0

In [46]:
unemployment_df.to_csv('unemploymentcombine.csv', index=False, header=True)