In [1]:
# import dependencies
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# read csv file
file_path = "countypres_2000-2016.csv"

# create the data frame 
pres_df = pd.read_csv(file_path)
pres_df.head()

,year,state,state_po,county,FIPS,office,candidate,party,candidatevotes,totalvotes,version
0,2000,Alabama,AL,Autauga,1001.0,President,Al Gore,democrat,4942.0,17208,20191203
1,2000,Alabama,AL,Autauga,1001.0,President,George W. Bush,republican,11993.0,17208,20191203
2,2000,Alabama,AL,Autauga,1001.0,President,Ralph Nader,green,160.0,17208,20191203
3,2000,Alabama,AL,Autauga,1001.0,President,Other,NaN,113.0,17208,20191203
4,2000,Alabama,AL,Baldwin,1003.0,President,Al Gore,democrat,13997.0,56480,20191203

In [3]:
#pres_df.columns=['year','state','state_po','county','office','candidate','party','candidatevotes','totalvotes']
#pres_df.head()
pres_df = pres_df.drop(columns=['FIPS', 'version'])
pres_df.head()

,year,state,state_po,county,office,candidate,party,candidatevotes,totalvotes
0,2000,Alabama,AL,Autauga,President,Al Gore,democrat,4942.0,17208
1,2000,Alabama,AL,Autauga,President,George W. Bush,republican,11993.0,17208
2,2000,Alabama,AL,Autauga,President,Ralph Nader,green,160.0,17208
3,2000,Alabama,AL,Autauga,President,Other,NaN,113.0,17208
4,2000,Alabama,AL,Baldwin,President,Al Gore,democrat,13997.0,56480

In [4]:
#dropping # of years not needed

pres_df = pres_df[pres_df.year != 2000]
pres_df = pres_df[pres_df.year != 2004]
pres_df = pres_df[pres_df.year != 2008]
pres_df = pres_df[pres_df.year != 2012]
pres_df.head()

,year,state,state_po,county,office,candidate,party,candidatevotes,totalvotes
40517,2016,Alabama,AL,Autauga,President,Hillary Clinton,democrat,5936.0,24973
40518,2016,Alabama,AL,Autauga,President,Donald Trump,republican,18172.0,24973
40519,2016,Alabama,AL,Autauga,President,Other,NaN,865.0,24973
40520,2016,Alabama,AL,Baldwin,President,Hillary Clinton,democrat,18458.0,95215
40521,2016,Alabama,AL,Baldwin,President,Donald Trump,republican,72883.0,95215

In [5]:
#renaming columns
pres_df = pres_df.rename(columns={"state": "State", "state_po": "State Abbreviation", "county": "County",
                                    "office": "Office", "candidate": "Candidate", "party": "Party",
                                    "candidatevotes": "Candidate Votes", "totalvotes": "Total Votes"})
pres_df.head()

,year,State,State Abbreviation,County,Office,Candidate,Party,Candidate Votes,Total Votes
40517,2016,Alabama,AL,Autauga,President,Hillary Clinton,democrat,5936.0,24973
40518,2016,Alabama,AL,Autauga,President,Donald Trump,republican,18172.0,24973
40519,2016,Alabama,AL,Autauga,President,Other,NaN,865.0,24973
40520,2016,Alabama,AL,Baldwin,President,Hillary Clinton,democrat,18458.0,95215
40521,2016,Alabama,AL,Baldwin,President,Donald Trump,republican,72883.0,95215

In [6]:
# change NaN values to 0
pres_df.fillna(0, inplace=True)
pres_df.head()

,year,State,State Abbreviation,County,Office,Candidate,Party,Candidate Votes,Total Votes
40517,2016,Alabama,AL,Autauga,President,Hillary Clinton,democrat,5936.0,24973
40518,2016,Alabama,AL,Autauga,President,Donald Trump,republican,18172.0,24973
40519,2016,Alabama,AL,Autauga,President,Other,0,865.0,24973
40520,2016,Alabama,AL,Baldwin,President,Hillary Clinton,democrat,18458.0,95215
40521,2016,Alabama,AL,Baldwin,President,Donald Trump,republican,72883.0,95215

In [7]:
# Create a new column with the % of the vote that the candidate received
pres_df["Candidate Percent"] = pres_df["Candidate Votes"] / pres_df["Total Votes"]
pres_df.head()

,year,State,State Abbreviation,County,Office,Candidate,Party,Candidate Votes,Total Votes,Candidate Percent
40517,2016,Alabama,AL,Autauga,President,Hillary Clinton,democrat,5936.0,24973,0.237697
40518,2016,Alabama,AL,Autauga,President,Donald Trump,republican,18172.0,24973,0.727666
40519,2016,Alabama,AL,Autauga,President,Other,0,865.0,24973,0.034637
40520,2016,Alabama,AL,Baldwin,President,Hillary Clinton,democrat,18458.0,95215,0.193856
40521,2016,Alabama,AL,Baldwin,President,Donald Trump,republican,72883.0,95215,0.765457

In [8]:
# Export the cleaned data tocsv
pres_df.to_csv("Clean Data/pres_overall_2016_clean.csv", index=False)