In [1]:
# import dependencies
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# read csv file
file_path = "1976-2018-senate.csv"

# create the data frame 
senate_df = pd.read_csv(file_path, encoding='iso-8859-1')
senate_df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version
0,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Sam Steiger,republican,False,total,321236,741210,False,20171011.0
1,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Wm. Mathews Feighan,independent,False,total,1565,741210,False,20171011.0
2,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Dennis DeConcini,democrat,False,total,400334,741210,False,20171011.0
3,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Allan Norwitz,libertarian,False,total,7310,741210,False,20171011.0
4,1976,Arizona,AZ,4,86,61,US Senate,statewide,gen,False,Bob Field,independent,False,total,10765,741210,False,20171011.0

In [3]:
# dropping # of years we do not need
senate_df = senate_df[senate_df.year != 1976]
senate_df = senate_df[senate_df.year != 1978]
senate_df = senate_df[senate_df.year != 1980]
senate_df = senate_df[senate_df.year != 1982]
senate_df = senate_df[senate_df.year != 1984]
senate_df = senate_df[senate_df.year != 1986]
senate_df = senate_df[senate_df.year != 1988]
senate_df = senate_df[senate_df.year != 1990]
senate_df = senate_df[senate_df.year != 1992]
senate_df = senate_df[senate_df.year != 1994]
senate_df = senate_df[senate_df.year != 1996]
senate_df = senate_df[senate_df.year != 1998]
senate_df = senate_df[senate_df.year != 2000]
senate_df = senate_df[senate_df.year != 2002]
senate_df = senate_df[senate_df.year != 2004]
senate_df = senate_df[senate_df.year != 2006]
senate_df = senate_df[senate_df.year != 2008]
senate_df = senate_df[senate_df.year != 2010]
senate_df = senate_df[senate_df.year != 2012]
senate_df = senate_df[senate_df.year != 2014]
senate_df = senate_df[senate_df.year != 2018]
senate_df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version
3048,2016,Alabama,AL,1,63,41,US Senate,statewide,gen,False,Ron Crumpton,democrat,False,total,748709,2087444,False,20171011.0
3049,2016,Alabama,AL,1,63,41,US Senate,statewide,gen,False,Richard C. Shelby,republican,False,total,1335104,2087444,False,20171011.0
3050,2016,Alabama,AL,1,63,41,US Senate,statewide,gen,False,NaN,NaN,True,total,3631,2087444,False,20171011.0
3051,2016,Alaska,AK,2,94,81,US Senate,statewide,gen,False,Joe Miller,libertarian,False,total,90825,311441,False,20171011.0
3052,2016,Alaska,AK,2,94,81,US Senate,statewide,gen,False,Ted Gianoutsos,independent,False,total,1758,311441,False,20171011.0

In [5]:
#dropping columns
senate_df = senate_df.drop(columns=["year", "state_fips", "state_cen", "state_ic", "office", "stage", 
                                  "mode", "unofficial", "version"])
senate_df.head()

,state,state_po,district,special,candidate,party,writein,candidatevotes,totalvotes
3048,Alabama,AL,statewide,False,Ron Crumpton,democrat,False,748709,2087444
3049,Alabama,AL,statewide,False,Richard C. Shelby,republican,False,1335104,2087444
3050,Alabama,AL,statewide,False,NaN,NaN,True,3631,2087444
3051,Alaska,AK,statewide,False,Joe Miller,libertarian,False,90825,311441
3052,Alaska,AK,statewide,False,Ted Gianoutsos,independent,False,1758,311441

In [7]:
#renaming columns
senate_df = senate_df.rename(columns={"state": "State", "state_po": "State Abbreviation", "district": "District Number",
                                    "special": "Special Election", "candidate": "Candidate", "party": "Party",
                                    "candidatevotes": "Candidate Votes", "totalvotes": "Total Votes"})
senate_df.head()

,State,State Abbreviation,District Number,Special Election,Candidate,Party,writein,Candidate Votes,Total Votes
3048,Alabama,AL,statewide,False,Ron Crumpton,democrat,False,748709,2087444
3049,Alabama,AL,statewide,False,Richard C. Shelby,republican,False,1335104,2087444
3050,Alabama,AL,statewide,False,NaN,NaN,True,3631,2087444
3051,Alaska,AK,statewide,False,Joe Miller,libertarian,False,90825,311441
3052,Alaska,AK,statewide,False,Ted Gianoutsos,independent,False,1758,311441

In [8]:
# Create a new column with the % of the vote that the candidate received
senate_df["Candidate Percent"] = senate_df["Candidate Votes"] / senate_df["Total Votes"]
senate_df.head()

,State,State Abbreviation,District Number,Special Election,Candidate,Party,writein,Candidate Votes,Total Votes,Candidate Percent
3048,Alabama,AL,statewide,False,Ron Crumpton,democrat,False,748709,2087444,0.358673
3049,Alabama,AL,statewide,False,Richard C. Shelby,republican,False,1335104,2087444,0.639588
3050,Alabama,AL,statewide,False,NaN,NaN,True,3631,2087444,0.001739
3051,Alaska,AK,statewide,False,Joe Miller,libertarian,False,90825,311441,0.291628
3052,Alaska,AK,statewide,False,Ted Gianoutsos,independent,False,1758,311441,0.005645

In [11]:
# change NaN values to 0
senate_df.fillna(0, inplace=True)
senate_df.head()

,State,State Abbreviation,District Number,Special Election,Candidate,Party,writein,Candidate Votes,Total Votes,Candidate Percent
3048,Alabama,AL,statewide,False,Ron Crumpton,democrat,False,748709,2087444,0.358673
3049,Alabama,AL,statewide,False,Richard C. Shelby,republican,False,1335104,2087444,0.639588
3050,Alabama,AL,statewide,False,0,0,True,3631,2087444,0.001739
3051,Alaska,AK,statewide,False,Joe Miller,libertarian,False,90825,311441,0.291628
3052,Alaska,AK,statewide,False,Ted Gianoutsos,independent,False,1758,311441,0.005645

In [13]:
# Export the cleaned data tocsv
senate_df.to_csv("Clean Data/senate_overall_2016_clean.csv", index=False)